export const entries: string[] = [
  'owns five Blåhaj',
  'once successfully plugged in a USB cable on the first try',
  'has met Hatsune Miku',
  'regularly [contributes](https://github.com/olivvybee/wellness-director) to open source Fedi bots',
  'understands how to configure and use NixOS',
  'installed GoToSocial on a toaster',
  'once travelled on a Deutsche Bahn ICE that arrived on time',
  'owns three ThinkPad X230s',
  'deleted the system32 folder',
  'always makes sure plushies are tucked into bed',
  'created a new neoemoji set',
  'once calculated pi to 1312 digits',
  'can fold a fitted sheet',
  'owns a tungsten cube',
  'can play the guitar, but has never played Wonderwall',
  'has never been sponsored by Raid Shadow Legends',
  'uploaded a mildly popular Flash animation to Newgrounds',
  'has edited Wikipedia on multiple occasions',
  'can say :3 out loud',
  'watches cat videos every night before bed',
  'once avoided Fedi meta for over 15 minutes',
  'wears thigh highs at all times',
  'has never paid for a TV License',
  'screams back at foxes',
  'always uses Oxford commas',
  'has been bitten by 16 different catgirls',
  'has blue hair and pronouns',
  'has a drawer full of bulging lithium batteries',
  'can whistle mostly in tune',
  'is learning Toki Pona',
  'has a 628 day streak on Duolingo',
  'is up to date with One Piece',
  "doesn't play a stealth archer in Skyrim",
  'drinks 1.5 litres of water per day',
  'finished the Blender donut tutorial',
  'has never been given a speeding ticket',
  'uses an AeroPress to make coffee',
  'gives the middle finger to passing Cybertrucks',
  'is part of a polycule with 142 members',
  'has ridden different 374 roller coasters',
  'prefers the Star Wars sequel trilogy',
  'snuggles with a plushie every night',
  'always buys the on-ride photos at theme parks',
  'says "slay" instead of "based"',
  'has seen every episode of SpongeBob SquarePants',
  'enjoys wearing spinny skirts',
  'can manually decode a QR code',
  'has visited every UK train station',
  'only forgets to take medication once a week',
  'has over 200,000 Gamerscore',
  'proved that P = NP',
  "can solve a Rubik's cube in less than 8 hours",
  'takes a pencil during every IKEA visit',
  'stores clothes in alphabetical order',
  'walks uphill both ways to and from work',
  'has unlocked everything in Balatro',
  'owns 118 domain names',
  'wears a wristwatch that is stuck showing 9:37 pm',
  'sometimes tries different pronouns for fun',
  'has never had a Twitter account',
  'meows in public',
  'logs every train journey',
  'lets coffee go cold before drinking it',
  'has over 70 platinum trophies',
  'has a Steam library containing over 1500 games, but has only played 32 of them',
  'hosts a website on a Nintendo 3DS',
  'never puts phones in a case',
  'once used the Lille Loophole to sneak into the UK',
  'is afraid of plane toilets',
  'is both a dog person and a cat person',
  'has a serial number',
  'has a vinyl collection, but no record player',
  'generates a weak magnetic field',
  'uses the Dvorak keyboard layout',
  'makes homemade Ethernet cables cut to just the right length',
  'can produce mind-boggling effects',
  'always turns on the subtitles',
  'is always precisely 8 minutes and 48 seconds early for appointments',
  "has a lot of ideas for games but hasn't yet made one",
  'wants to write a Fedi client',
  'cannot start eating without finding something to watch',
  'does not boost posts that have images without alt text',
  'reads the last page of a book before starting it',
  'reclines the seat as far as possible on planes',
  'prefers to count in base 16',
  'can name the hex code for any colour by sight alone',
  'sits by the window when waiting for a package',
  'was once whacked with a wet trout',
  'always sets the TV volume to an even number',
  'owns 14 of the same outfit',
  'switches Linux distros every other week',
  'has reached level 1810 in Candy Crush',
  'wants a tattoo, but cannot decide what to get',
  'actually knows how to play Minesweeper',
  'wears headphones the wrong way round',
  'still uses Python 2',
  'refuses to update to Windows 11',
  'has never finished a project before starting a new one',
  'has an elaborate Home Assistant setup',
  'once finished an entire chapstick',
];
