export const entries: string[] = [
  'owns five Blåhaj',
  'once successfully plugged in a USB cable on the first try',
  'has met Hatsune Miku',
  'regularly [contributes](https://github.com/olivvybee/wellness-director) to open source Fedi bots',
  'understands how to configure and use NixOS',
  'installed GoToSocial on a toaster',
  'once travelled on a Deutsche Bahn ICE that arrived on time',
  'owns three ThinkPad X230s',
  'deleted the system32 folder',
  'always makes sure plushies are tucked into bed',
  'created a new neoemoji set',
  'once calculated pi to 1312 digits',
  'can fold a fitted sheet',
  'owns a tungsten cube',
  'can play the guitar, but has never played Wonderwall',
  'has never been sponsored by Raid Shadow Legends',
  'uploaded a mildly popular Flash animation to Newgrounds',
  'has edited Wikipedia on multiple occasions',
  'can say :3 out loud',
  'watches cat videos every night before bed',
  'once avoided Fedi meta for over 15 minutes',
  'wears thigh highs at all times',
  'has never paid for a TV License',
  'screams back at foxes',
  'always uses Oxford commas',
  'has been bitten by 16 different catgirls',
  'has blue hair and pronouns',
  'has a drawer full of bulging lithium batteries',
  'can whistle mostly in tune',
  'is learning Toki Pona',
  'knows how to use Fusion 360',
  'has a 628 day streak on Duolingo',
  'is up to date with One Piece',
  "doesn't play a stealth archer in Skyrim",
  'drinks 1.5 litres of water per day',
  'finished the Blender donut tutorial',
  'has never been given a speeding ticket',
  'uses an AeroPress to make coffee',
  'gives the middle finger to passing Cybertrucks',
  'is part of a polycule with 42 members',
  'has ridden different 374 roller coasters',
  'prefers the Star Wars sequel trilogy',
  'snuggles with a plushie every night',
  'always buys the on-ride photos at theme parks',
  'says "slay" instead of "based"',
  'has seen every episode of SpongeBob SquarePants',
  'enjoys wearing spinny skirts',
  'can manually decode a QR code',
  'has visited every UK train station',
  'only forgets to take medication once a week',
  'has over 200,000 Gamerscore',
  'proved that P = NP',
  "can solve a Rubik's cube in under 8 minutes",
  'takes a pencil during every IKEA visit',
  'stores clothes in alphabetical order',
  'walks uphill both ways to and from work',
  'has unlocked everything in Balatro',
  'owns 118 domain names',
  'wears a wristwatch that is stuck showing 9:37 pm',
  'sometimes tries different pronouns for fun',
  'has never had a Twitter account',
  'meows in public',
  'logs every train journey',
  'lets coffee go cold before drinking it',
  'has over 30 platinum trophies',
  'has a Steam library containing over 1500 games, but has only played 32 of them',
  'hosts a website on a Nintendo 3DS',
  'never puts phones in a case',
  'once used the Lille Loophole to sneak into the UK',
  'is afraid of plane toilets',
  'is both a dog person and a cat person',
  'has a serial number',
  'has a vinyl collection, but no record player',
  'generates a weak magnetic field',
  'uses the Dvorak keyboard layout',
];
